### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by fabcooldog** [stanley-godfrey/almanac-pages#2]
##The following tasks need to be completed to further progress the website
###The number of exclamation marks (**!**) a task has, the more important it is.

- [ ] (**!!**) Create a main title/introductory page linking recent or featured articles
- [ ] (**!!**) Create some articles!
- [ ] (**!**) Look into monetisation streams- [Amazon Ads](https://affiliate-program.amazon.com/welcome) look good

**Comment by stanley-godfrey** [comment]
I'm moving the to-do list into a md file. I don't like the phrase issue
